apiVersion: v1
kind: Service
metadata:
  name: result-lb
  labels:
    name: result-lb
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    name: result-app-pod
    app: demo-voting-app
