apiVersion: v1
kind: Service
metadata:
  name: voting-lb
  labels:
    name: voting-lb
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    name: voting-app-pod
    app: demo-voting-app
