apiVersion: v1
kind: Pod
metadata:
  name : my-pod-with-pv
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - mountPath: /var/www/html
      name: my-volume
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc
