apiVersion: v1
kind: Pod
metadata:
  name: my-pod-with-toleration
  labels:
    app: app1
spec:
  containers:
  - name: nginx-container
    image: nginx

  tolerations:
  - key: "app"
    operator: "Equal"
    value: "my-app"
    effect: "NoSchedule"
