apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: 250m # equivalent to 0.25
      limits:
        memory: "128Mi"
        cpu: 4
