# the difference between a StatefulSet and a Deployment is that a 
# StatefulSet maintains a sticky identity for each of their Pods. 
# These pods are created from the same spec, but are not interchangeable: 
# each has a persistent identifier that it maintains across any rescheduling.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset
  labels:
    app: mysql
spec:
  serviceName: mysql-h # headless service
  replicas: 3
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
  template:
    metadata:
      name: myapp-pod
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
  # podManagementPolicy: Parallel # or OrderedReady (default)
  volumeClaimTemplates:
  # each pod will have its own PVC
  - metadata:
      name: my-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 500Mi
