apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    name: worker-deploy
spec:
  replicas: 1
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: demo-voting-app
    spec:
      containers:
      - name: worker-app
        image: dockersamples/examplevotingapp_worker
  selector:
    matchLabels:
      name: worker-pod
      app: demo-voting-app
